name: eventia2-dev
services:
  eventia2-db:
    image: mariadb:11.3.2
    container_name: eventia2-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - eventia2_dev_data:/var/lib/mysql

volumes:
  eventia2_dev_data: