spring.application.name=eventia
spring.profiles.default=prod
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect